In [2]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_boston

In [15]:
boston=load_boston()
boston.keys()

dict_keys(['data', 'target', 'feature_names', 'DESCR', 'filename'])

In [16]:
boston.data

array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
        4.9800e+00],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
        9.1400e+00],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
        4.0300e+00],
       ...,
       [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        5.6400e+00],
       [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
        6.4800e+00],
       [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        7.8800e+00]])

In [17]:
boston.target

array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
       18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
       15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
       13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
       21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
       35.4, 24.7, 31.6, 23.3, 19.6, 18.7, 16. , 22.2, 25. , 33. , 23.5,
       19.4, 22. , 17.4, 20.9, 24.2, 21.7, 22.8, 23.4, 24.1, 21.4, 20. ,
       20.8, 21.2, 20.3, 28. , 23.9, 24.8, 22.9, 23.9, 26.6, 22.5, 22.2,
       23.6, 28.7, 22.6, 22. , 22.9, 25. , 20.6, 28.4, 21.4, 38.7, 43.8,
       33.2, 27.5, 26.5, 18.6, 19.3, 20.1, 19.5, 19.5, 20.4, 19.8, 19.4,
       21.7, 22.8, 18.8, 18.7, 18.5, 18.3, 21.2, 19.2, 20.4, 19.3, 22. ,
       20.3, 20.5, 17.3, 18.8, 21.4, 15.7, 16.2, 18. , 14.3, 19.2, 19.6,
       23. , 18.4, 15.6, 18.1, 17.4, 17.1, 13.3, 17.8, 14. , 14.4, 13.4,
       15.6, 11.8, 13.8, 15.6, 14.6, 17.8, 15.4, 21

In [19]:
boston.feature_names

array(['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD',
       'TAX', 'PTRATIO', 'B', 'LSTAT'], dtype='<U7')

In [20]:
boston.DESCR

".. _boston_dataset:\n\nBoston house prices dataset\n---------------------------\n\n**Data Set Characteristics:**  \n\n    :Number of Instances: 506 \n\n    :Number of Attributes: 13 numeric/categorical predictive. Median Value (attribute 14) is usually the target.\n\n    :Attribute Information (in order):\n        - CRIM     per capita crime rate by town\n        - ZN       proportion of residential land zoned for lots over 25,000 sq.ft.\n        - INDUS    proportion of non-retail business acres per town\n        - CHAS     Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)\n        - NOX      nitric oxides concentration (parts per 10 million)\n        - RM       average number of rooms per dwelling\n        - AGE      proportion of owner-occupied units built prior to 1940\n        - DIS      weighted distances to five Boston employment centres\n        - RAD      index of accessibility to radial highways\n        - TAX      full-value property-tax rate per $10,000

In [21]:
#lets convet all into DataFrame

In [24]:
bos=pd.DataFrame(boston.data,columns=boston.feature_names)
bos

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0    0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1    0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2    0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3    0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4    0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...    ...   
501  0.06263   0.0  11.93   0.0  0.573  6.593  69.1  2.4786  1.0  273.0   
502  0.04527   0.0  11.93   0.0  0.573  6.120  76.7  2.2875  1.0  273.0   
503  0.06076   0.0  11.93   0.0  0.573  6.976  91.0  2.1675  1.0  273.0   
504  0.10959   0.0  11.93   0.0  0.573  6.794  89.3  2.3889  1.0  273.0   
505  0.04741   0.0  11.93   0.0  0.573  6.030  80.8  2.5050  1.0  273.0   

     PTRATIO       B  LSTAT  
0       15.3  396.90   4.98  
1       17.8  396.90   9.14  
2       17.8  392.83   4.03  
3       18.7  394.63   2.94  
4       18.7  396.90   5.33  
..       ...     ...    ...  
501     21.0  391.99   9.67  
502     21.0  396.90   9.08  
503     21.0  396.90   5.64  
504     21.0  393.45   6.48  
505     21.0  396.90   7.88  

[506 rows x 13 columns]

In [25]:
bos.shape

(506, 13)

In [29]:
#adding target columns into it
bos['target']=boston.target

In [30]:
bos.columns

Index(['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX',
       'PTRATIO', 'B', 'LSTAT', 'target'],
      dtype='object')

In [31]:
#lets check the shape
bos.shape

(506, 14)

In [32]:
#lets check the null values
bos.isnull().any()

CRIM       False
ZN         False
INDUS      False
CHAS       False
NOX        False
RM         False
AGE        False
DIS        False
RAD        False
TAX        False
PTRATIO    False
B          False
LSTAT      False
target     False
dtype: bool

As we can see that there is no null values in the dataset

In [33]:
bos.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  target  
0     15.3  396.90   4.98    24.0  
1     17.8  396.90   9.14    21.6  
2     17.8  392.83   4.03    34.7  
3     18.7  394.63   2.94    33.4  
4     18.7  396.90   5.33    36.2

here we can see that there is no categorical caumns in the dataset

In [34]:
#lets divid and store it into x and y variable

In [35]:
x=bos.iloc[:,:-1]
x.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  
0     15.3  396.90   4.98  
1     17.8  396.90   9.14  
2     17.8  392.83   4.03  
3     18.7  394.63   2.94  
4     18.7  396.90   5.33

In [36]:
y=bos.iloc[:,-1]
y.head()

0    24.0
1    21.6
2    34.7
3    33.4
4    36.2
Name: target, dtype: float64

In [37]:
#lets scale down the dataset
from sklearn.preprocessing import MinMaxScaler

In [38]:
scaler=MinMaxScaler()

In [39]:
sc=scaler.fit_transform(x)
sc

array([[0.00000000e+00, 1.80000000e-01, 6.78152493e-02, ...,
        2.87234043e-01, 1.00000000e+00, 8.96799117e-02],
       [2.35922539e-04, 0.00000000e+00, 2.42302053e-01, ...,
        5.53191489e-01, 1.00000000e+00, 2.04470199e-01],
       [2.35697744e-04, 0.00000000e+00, 2.42302053e-01, ...,
        5.53191489e-01, 9.89737254e-01, 6.34657837e-02],
       ...,
       [6.11892474e-04, 0.00000000e+00, 4.20454545e-01, ...,
        8.93617021e-01, 1.00000000e+00, 1.07891832e-01],
       [1.16072990e-03, 0.00000000e+00, 4.20454545e-01, ...,
        8.93617021e-01, 9.91300620e-01, 1.31070640e-01],
       [4.61841693e-04, 0.00000000e+00, 4.20454545e-01, ...,
        8.93617021e-01, 1.00000000e+00, 1.69701987e-01]])

In [40]:
#lets import train test split

In [41]:
from sklearn.model_selection import train_test_split

In [42]:
X_train,x_test,Y_train,y_test=train_test_split(sc,y,test_size=0.3)

In [43]:
X_train.shape

(354, 13)

In [44]:
Y_train.shape

(354,)

In [45]:
#lets start ANN

In [46]:
from keras.models import Sequential
from keras.layers import Dense

In [47]:
#lets instatiate sequatinal
model=Sequential()

In [48]:
model.add(Dense(15,input_shape=(13,),activation='relu'))

In [49]:
model.add(Dense(10,activation='relu'))

In [50]:
model.add(Dense(5,activation='relu'))

In [51]:
model.add(Dense(1,activation='linear'))

In [52]:
#lets check the summary 

In [53]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 15)                210       
_________________________________________________________________
dense_1 (Dense)              (None, 10)                160       
_________________________________________________________________
dense_2 (Dense)              (None, 5)                 55        
_________________________________________________________________
dense_3 (Dense)              (None, 1)                 6         
Total params: 431
Trainable params: 431
Non-trainable params: 0
_________________________________________________________________


In [54]:
#lets compile the model

In [55]:
model.compile(loss='mse',optimizer='Adam',metrics=['mse','mae'])

In [56]:
#lets check the result

In [62]:
result=model.fit(X_train,Y_train,batch_size=150,epochs=100)

Epoch 1/100
3/3 [==============================] - 0s 1ms/step - loss: 49.6556 - mse: 49.6556 - mae: 5.0315
Epoch 2/100
3/3 [==============================] - 0s 2ms/step - loss: 49.4118 - mse: 49.4118 - mae: 5.0322
Epoch 3/100
3/3 [==============================] - 0s 3ms/step - loss: 49.2439 - mse: 49.2439 - mae: 5.0356
Epoch 4/100
3/3 [==============================] - 0s 2ms/step - loss: 49.0694 - mse: 49.0694 - mae: 5.0359
Epoch 5/100
3/3 [==============================] - 0s 3ms/step - loss: 48.9026 - mse: 48.9026 - mae: 5.0317
Epoch 6/100
3/3 [==============================] - 0s 3ms/step - loss: 48.7182 - mse: 48.7182 - mae: 5.0168
Epoch 7/100
3/3 [==============================] - 0s 3ms/step - loss: 48.5459 - mse: 48.5459 - mae: 4.9998
Epoch 8/100
3/3 [==============================] - 0s 2ms/step - loss: 48.3832 - mse: 48.3832 - mae: 4.9859
Epoch 9/100
3/3 [==============================] - 0s 3ms/step - loss: 48.2316 - mse: 48.2316 - mae: 4.9743
Epoch 10/100
3/3 [==========

3/3 [==============================] - 0s 5ms/step - loss: 34.6297 - mse: 34.6297 - mae: 4.1581
Epoch 77/100
3/3 [==============================] - 0s 3ms/step - loss: 34.4174 - mse: 34.4174 - mae: 4.1502
Epoch 78/100
3/3 [==============================] - 0s 4ms/step - loss: 34.1862 - mse: 34.1862 - mae: 4.1519
Epoch 79/100
3/3 [==============================] - 0s 3ms/step - loss: 34.0419 - mse: 34.0419 - mae: 4.1617
Epoch 80/100
3/3 [==============================] - ETA: 0s - loss: 38.2868 - mse: 38.2868 - mae: 4.265 - 0s 3ms/step - loss: 33.8650 - mse: 33.8650 - mae: 4.1598
Epoch 81/100
3/3 [==============================] - 0s 2ms/step - loss: 33.6586 - mse: 33.6586 - mae: 4.1430
Epoch 82/100
3/3 [==============================] - 0s 3ms/step - loss: 33.4467 - mse: 33.4467 - mae: 4.1158
Epoch 83/100
3/3 [==============================] - 0s 5ms/step - loss: 33.2683 - mse: 33.2683 - mae: 4.0903
Epoch 84/100
3/3 [==============================] - 0s 3ms/step - loss: 33.1458 - mse: 

In [63]:
#evaluating the model

In [64]:
model.evaluate(x_test,y_test)

5/5 [==============================] - 1s 2ms/step - loss: 24.8148 - mse: 24.8148 - mae: 3.6773


[24.81481170654297, 24.81481170654297, 3.6773436069488525]